### ISSUE TITLE
UnpicklingError: invalid load key, '\x0a'

### ISSUE THREAD

**Issue by miramira227** [yhenon/pytorch-retinanet#138]
I'm trying to validate this model by using colab, and the Unpickling Error occurred like below: 

Traceback (most recent call last):
  File "coco_validation.py", line 51, in <module>
    main()
  File "coco_validation.py", line 40, in main
    retinanet.load_state_dict(torch.load(parser.model_path, map_location=torch.device('cuda')))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.

I've googled a lot to search the answer but the only thing that I've got is that this problem is related to the range of something... 

Thank you in advance

**Comment by Ankita-020696** [comment]
@miramira227 I am facing same issue, did you find solution?

Thanks
