### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (960,1280,4) (1,1,3)

### ISSUE THREAD

**Issue by 447226268** [yhenon/pytorch-retinanet#147]
CUDA available: True
Num training images: 135951
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    main()
  File "train.py", line 121, in main
    for iter_num, data in enumerate(dataloader_train):
  File "/home/zhouxin/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zhouxin/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhouxin/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhouxin/training/experiment/task3/pytorch-retinanet/retinanet/dataloader.py", line 210, in __getitem__
    sample = self.transform(sample)
  File "/home/zhouxin/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 70, in __call__
    img = t(img)
  File "/home/zhouxin/training/experiment/task3/pytorch-retinanet/retinanet/dataloader.py", line 410, in __call__
    return {'img':((image.astype(np.float32)-self.mean)/self.std), 'annot': annots}
ValueError: operands could not be broadcast together with shapes (960,1280,4) (1,1,3) 

I dont know what is wrong with it. It caused by my custom dataset?

**Comment by giveshot** [comment]
i got the same problem too, and it turns out that some images in my custom dataset have a shape of (1024,1024,4) with 4 replicated channels.
you can check your dataset and fix it in dataloader.py

**Comment by JDehais-public** [comment]
Fixed for me by changing file from png with RGBA channels to jpg with RGB.

**Comment by devendraswamy** [comment]
File "/media/swamy/Ubuntu/AppsTek/Retinanet/pytorch-retinanet/retinanet/dataloader.py", line 410, in __call__
    return {'img':((image.astype(np.float32)-self.mean)/self.std), 'annot': annots}
ValueError: operands could not be broadcast together with shapes (224,478,4) (1,1,3) 

please be help , Thank you
