### ISSUE TITLE
How to resume training from last epoch?

### ISSUE THREAD

**Issue by suarezjessie** [yhenon/pytorch-retinanet#157]
My training was interrupted and I need to resume training from the last epoch. I put this snippet
```
retinanet = model.resnet50(num_classes=dataset_train.num_classes(),)
retinanet.load_state_dict(torch.load(PATH_TO_WEIGHTS))
```

In the following if-else statements to load the pretrained weights
```
 # Create the model
    if parser.depth == 18:
        retinanet = model.resnet18(num_classes=dataset_train.num_classes(), pretrained=True)
    elif parser.depth == 34:
        retinanet = model.resnet34(num_classes=dataset_train.num_classes(), pretrained=True)
    elif parser.depth == 50:
        retinanet = model.resnet50(num_classes=80, pretrained=True)
        retinanet.load_state_dict(torch.load(PATH_TO_WEIGHTS))
    elif parser.depth == 101:
        retinanet = model.resnet101(num_classes=dataset_train.num_classes(), pretrained=True)
    elif parser.depth == 152:
        retinanet = model.resnet152(num_classes=dataset_train.num_classes(), pretrained=True)
```

It worked for training using the pretrained weights but when I tried resuming the training using the same method (which is by replacing the `PATH_TO_WEIGHTS` with the path to my trained model of a few epochs, it throws this error
```
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    main()
  File "train.py", line 86, in main
    retinanet.load_state_dict(torch.load('csv_retinanet_29.pt'))
  File "/home/jessie.suarez/.conda/envs/cs298_anomaly_localization_retinanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 818, in load_state_dict
    state_dict = state_dict.copy()
  File "/home/jessie.suarez/.conda/envs/cs298_anomaly_localization_retinanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'ResNet' object has no attribute 'copy'
```

Any help would be appreciated. It already took me a few days to run the initial epochs. I don't wanna re-run it again.

Thanks

**Comment by suarezjessie** [comment]
Solved the issue, I used this code. Instead of using the snippet, I used `torch.load`. The sample code is below

```
# Create the model
    if parser.depth == 18:
        retinanet = model.resnet18(num_classes=dataset_train.num_classes(), pretrained=True)
    elif parser.depth == 34:
        retinanet = model.resnet34(num_classes=dataset_train.num_classes(), pretrained=True)
    elif parser.depth == 50:
        # retinanet = model.resnet50(num_classes=80, pretrained=True)
        # retinanet.load_state_dict(torch.load(PATH_TO_WEIGHTS))
        retinanet = torch.load(PATH_TO_TRAINED_MODEL)
    elif parser.depth == 101:
        retinanet = model.resnet101(num_classes=dataset_train.num_classes(), pretrained=True)
    elif parser.depth == 152:
        retinanet = model.resnet152(num_classes=dataset_train.num_classes(), pretrained=True)
```

**Comment by shenhaibb** [comment]
parser.add_argument('--resume', nargs='?', const=True, default=False, help='resume most recent training')

    if parser.depth == 18:
        retinanet = model.resnet18(num_classes=dataset_train.num_classes(), pretrained=True)
    elif parser.depth == 34:
        retinanet = model.resnet34(num_classes=dataset_train.num_classes(), pretrained=True)
    elif parser.depth == 50:
        if not parser.resume:
            retinanet = model.resnet50(num_classes=dataset_train.num_classes(), pretrained=True)
        else:
            retinanet = torch.load(parser.resume)
