### ISSUE TITLE
TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by soumochatterjee** [yhenon/pytorch-retinanet#175]
When I tried to run the command 
**!python train.py --dataset csv --csv_train ../training.csv  --csv_classes ../wheat_head_class_list.csv  --csv_val ../validation.csv**

got the error:
**CUDA available: True
Traceback (most recent call last):
  File "/content/pytorch-retinanet/retinanet/dataloader.py", line 166, in _parse
    return function(value)
ValueError: invalid literal for int() with base 10: '245.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 180, in <module>
    main()
  File "train.py", line 57, in main
    transform=transforms.Compose([Normalizer(), Augmenter(), Resizer()]))
  File "/content/pytorch-retinanet/retinanet/dataloader.py", line 153, in __init__
    self.image_data = self._read_annotations(csv.reader(file, delimiter=','), self.classes)
  File "/content/pytorch-retinanet/retinanet/dataloader.py", line 270, in _read_annotations
    x1 = self._parse(x1, int, 'line {}: malformed x1: {{}}'.format(line))
  File "/content/pytorch-retinanet/retinanet/dataloader.py", line 168, in _parse
    raise(ValueError(fmt.format(e)), None)
TypeError: exceptions must derive from BaseException**

Here's the link to my ntebook -->
[](https://colab.research.google.com/drive/1Wy3tk8h2z-lIknf1fKom-2_Ds6-yLY3q?usp=sharing)

**Comment by yhenon** [comment]
The important part is here:
`ValueError: invalid literal for int() with base 10: '245.0' `

It looks like your class file is messed up somehow? Could you post it here?

**Comment by soumochatterjee** [comment]
here I am posting out the files that I have created
![image](https://user-images.githubusercontent.com/42636586/87859619-0fef5380-c954-11ea-9039-538e1fb7d836.png)

**Comment by yhenon** [comment]
- You need to have only 1 bounding box per line, i.e.:

/data/imgs/img_001.jpg,837,346,981,456,wheat-head
/data/imgs/img_002.jpg,215,312,279,391,wheat-head
/data/imgs/img_002.jpg,22,5,89,84,wheat-head

Values should be int, not float, so `942.0` -> `942`
