### ISSUE TITLE
I converted pytorch model to onnx, but failed to run onnx.

### ISSUE THREAD

**Issue by ccl-private** [yhenon/pytorch-retinanet#217]
Here is my code.
`import torch
import torch.onnx
from retinanet import model

model= model.resnet50(num_classes=80,)
model.load_state_dict(torch.load('../models/coco_resnet_50_map_0_335_state_dict.pt'))
model=model.cuda()
dummy_input = torch.randn(1, 3, 608, 1024, device='cuda')
torch.onnx.export(model, dummy_input, "onnx_model_name.onnx", opset_version=11)

import onnx

model = onnx.load("onnx_model_name.onnx")

onnx.checker.check_model(model)

print(onnx.helper.printable_graph(model.graph))

import onnxruntime as ort
import numpy as np

ort_session = ort.InferenceSession('onnx_model_name.onnx')
input_name = ort_session.get_inputs()[0].name # 'data'
out = ort_session.get_outputs()
outputs = list()
for i in out:
outputs.append(i.name)
print(input_name)
print(outputs)

outputs = ort_session.run(outputs, input_feed={input_name: np.random.randn(1, 3, 608, 1024).astype(np.float32)})

print(outputs[0])`

**Comment by ccl-private** [comment]
Here is the error log:
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Concat node. Name:'Concat_711' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/concat.cc:72 onnxruntime::common::Status onnxruntime::ConcatBase::PrepareForCompute(onnxruntime::OpKernelContext*, const std::vector<const onnxruntime::Tensor*>&, onnxruntime::Prepare&) const inputs_n_rank == inputs_0_rank was false. Ranks of input data are different, cannot concatenate them. expected rank: 1 got: 2

**Comment by ccl-private** [comment]
can someone try conversion and run onnx?

**Comment by Sandeep418** [comment]
import os
import torch
import onnxruntime
import numpy as np
from torchvision import transforms
import cv2
from onnx import numpy_helper
import urllib

data_dir = 'test_data_set_0'
url, filename = ("https://github.com/onnx/models/raw/master/vision/object_detection_segmentation/retinanet/dependencies/demo.jpg", "demo.jpg")
urllib.request.urlretrieve(url, filename)

def flatten(inputs):
    return [[flatten(i) for i in inputs] if isinstance(inputs, (list, tuple)) else inputs]


def update_flatten_list(inputs, res_list):
    for i in inputs:
        res_list.append(i) if not isinstance(i, (list, tuple)) else update_flatten_list(i, res_list)
    return res_list


def to_numpy(x):
    if type(x) is not np.ndarray:
        x = x.detach().cpu().numpy() if x.requires_grad else x.cpu().numpy()
    return x


def save_tensor_proto(file_path, name, data):
    tp = numpy_helper.from_array(data)
    tp.name = name

    with open(file_path, 'wb') as f:
        f.write(tp.SerializeToString())


def save_data(test_data_dir, prefix, names, data_list):
    if isinstance(data_list, torch.autograd.Variable) or isinstance(data_list, torch.Tensor):
        data_list = [data_list]
    for i, d in enumerate(data_list):
        d = d.data.cpu().numpy()
        save_tensor_proto(os.path.join(test_data_dir, '{0}_{1}.pb'.format(prefix, i)), names[i], d)


def save_model(name, model, inputs, outputs, input_names=None, output_names=None, **kwargs):
    if hasattr(model, 'train'):
        model.train(False)
    dir = './'
    if not os.path.exists(dir):
        os.makedirs(dir)
    dir = os.path.join(dir, 'test_' + name)
    if not os.path.exists(dir):
        os.makedirs(dir)

    inputs_flatten = flatten(inputs)
    inputs_flatten = update_flatten_list(inputs_flatten, [])
    outputs_flatten = flatten(outputs)
    outputs_flatten = update_flatten_list(outputs_flatten, [])
    if input_names is None:
        input_names = []
        for i, _ in enumerate(inputs_flatten):
            input_names.append('input' + str(i+1))
    else:
        np.testing.assert_equal(len(input_names), len(inputs_flatten),
                                "Number of input names provided is not equal to the number of inputs.")

    if output_names is None:
        output_names = []
        for i, _ in enumerate(outputs_flatten):
            output_names.append('output' + str(i+1))
    else:
        np.testing.assert_equal(len(output_names), len(outputs_flatten),
                                "Number of output names provided is not equal to the number of output.")

    model_dir = os.path.join(dir, 'model.onnx')
    torch.onnx.export(model, inputs, model_dir, verbose=True, input_names=input_names,
                      output_names=output_names, example_outputs=outputs, **kwargs)

    test_data_dir = os.path.join(dir, data_dir)
    if not os.path.exists(test_data_dir):
        os.makedirs(test_data_dir)

    save_data(test_data_dir, "input", input_names, inputs_flatten)
    save_data(test_data_dir, "output", output_names, outputs_flatten)

    return model_dir, test_data_dir


def inference(file, inputs, outputs):
    inputs_flatten = flatten(inputs)
    inputs_flatten = update_flatten_list(inputs_flatten, [])
    outputs_flatten = flatten(outputs)
    outputs_flatten = update_flatten_list(outputs_flatten, [])

    sess = onnxruntime.InferenceSession(file)
    ort_inputs = dict((sess.get_inputs()[i].name, to_numpy(input)) for i, input in enumerate(inputs_flatten))
    res = sess.run(None, ort_inputs)

    if outputs is not None:
        print("== Checking model output ==")
        [np.testing.assert_allclose(to_numpy(output), res[i], rtol=1e-03, atol=1e-05) for i, output in enumerate(outputs_flatten)]
        print("== Done ==")


def torch_inference(model, input):
    print("====== Torch Inference ======")
    output=model(input)
    return output


def ort_inference(file, inputs_flatten, outputs_flatten):
    print("====== ORT Inference ======")
    ort_sess = onnxruntime.InferenceSession(file)
    ort_inputs = dict((ort_sess.get_inputs()[i].name, to_numpy(input)) for i, input in enumerate(inputs_flatten))
    ort_outs = ort_sess.run(None, ort_inputs)

    if outputs_flatten is not None:
        print("== Checking model output ==")
        [np.testing.assert_allclose(to_numpy(output), ort_outs[i], rtol=1e-03, atol=1e-05) for i, output in
         enumerate(outputs_flatten)]
    print("== Done ==")

model_path='model.pt'
model = torch.load(model_path)
model.eval()
model.exporting = True
input_image = cv2.imread(filename)
preprocess = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

image_orig = input_image.copy()

rows, cols, cns = input_image.shape

smallest_side = min(rows, cols)

# rescale the image so the smallest side is min_side
min_side = 608
max_side = 1024
scale = min_side / smallest_side

# check if the largest side is now greater than max_side, which can happen
# when images have a large aspect ratio
largest_side = max(rows, cols)

if largest_side * scale > max_side:
    scale = max_side / largest_side

# resize the image with the computed scale
image = cv2.resize(input_image, (int(round(cols * scale)), int(round((rows * scale)))))
rows, cols, cns = image.shape

pad_w = 32 - rows % 32
pad_h = 32 - cols % 32

new_image = np.zeros((rows + pad_w, cols + pad_h, cns)).astype(np.float32)
new_image[:rows, :cols, :] = image.astype(np.float32)
image = new_image.astype(np.float32)
image /= 255
image -= [0.485, 0.456, 0.406]
image /= [0.229, 0.224, 0.225]
image = np.expand_dims(image, 0)
image = np.transpose(image, (0, 3, 1, 2))
#input_tensor = preprocess(input_image)
input_tensor = torch.tensor(image)#input_tensor.unsqueeze(0)
output = torch_inference(model, (input_tensor).cuda())

# Test exported model with TensorProto data saved in files
inputs_flatten = flatten(input_tensor.detach().cpu().numpy())
inputs_flatten = update_flatten_list(inputs_flatten, [])
outputs_flatten = flatten(output)
outputs_flatten = update_flatten_list(outputs_flatten, [])

# model_dir, data_dir = save_model('retinanet_resnet101', model.cpu(), input_tensor, output, input_names=['input'],
#                                  opset_version=9)
model_dir, data_dir=save_model('retinanet_resnet101', model.cuda(), input_tensor.cuda(), output, input_names=['input'],
                                 opset_version=12)

ort_inference(model_dir, inputs_flatten, outputs_flatten)

**Comment by Sandeep418** [comment]
@ccl-private check this one to convert torch to onnx.
https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/retinanet/dependencies/retinanet-export.py

**Comment by dwaithe** [comment]
I had the same problem. It was the last concatenation:
finalAnchorBoxesCoordinates = torch.cat((finalAnchorBoxesCoordinates, anchorBoxes[anchors_nms_idx]))
Unlike the other concatenations onnx doesn't like it as anchorBoxes is 2-D, the others are 1-D. It's only the first loop of the for loop (i.e. i=0). Therefore you can initialise finalAnchorBoxesCoordinates as anchorBoxes for i =0 and then concatenate from there: 
 if i ==0: 
                  
                   finalAnchorBoxesCoordinates = anchorBoxes[anchors_nms_idx]
                else:
                   finalAnchorBoxesCoordinates = torch.cat((finalAnchorBoxesCoordinates, anchorBoxes[anchors_nms_idx]))

Worked for me.

**Comment by satpalsr** [comment]
Any of you successfully convert to onnx? 

I get these warnings.
```
TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  image_shape = np.array(image_shape)
pytorch-retinanet/retinanet/anchors.py:38: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  return torch.from_numpy(all_anchors.astype(np.float32)).cuda()
pytorch-retinanet/retinanet/model.py:268: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  finalScores = torch.Tensor([])
pytorch-retinanet/retinanet/model.py:269: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  finalAnchorBoxesIndexes = torch.Tensor([]).long()
pytorch-retinanet/retinanet/model.py:270: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  finalAnchorBoxesCoordinates = torch.Tensor([])
pytorch-retinanet/retinanet/model.py:280: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if scores_over_thresh.sum() == 0:
Traceback (most recent call last):
  File "torch2onnx.py", line 8, in <module>
    torch.onnx.export(model, dummy_input, 'model.onnx',verbose=False, input_names=input_names, output_names=output_names, export_params=True,  opset_version=11)
  File "pytorch-retinanet/env/lib/python3.6/site-packages/torch/onnx/__init__.py", line 320, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "pytorch-retinanet/env/lib/python3.6/site-packages/torch/onnx/utils.py", line 111, in export
    custom_opsets=custom_opsets, use_external_data_format=use_external_data_format)
  File "pytorch-retinanet/env/lib/python3.6/site-packages/torch/onnx/utils.py", line 729, in _export
    dynamic_axes=dynamic_axes)
  File "pytorch-retinanet/env/lib/python3.6/site-packages/torch/onnx/utils.py", line 501, in _model_to_graph
    module=module)
  File "pytorch-retinanet/env/lib/python3.6/site-packages/torch/onnx/utils.py", line 215, in _optimize_graph
    torch._C._jit_pass_onnx_set_dynamic_input_shape(graph, dynamic_axes, input_names)
TypeError: _jit_pass_onnx_set_dynamic_input_shape(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: Dict[str, Dict[int, str]], arg2: List[str]) -> None
```
