### ISSUE TITLE
NameError: name 'raise_from' is not defined

### ISSUE THREAD

**Issue by dspei** [yhenon/pytorch-retinanet#83]
`
when i train my csv dataset:
python train.py --dataset csv --csv_train '/home/subSda/KAIST/train_annots.csv' --csv_classes '/home/subSda/KAIST/class_list.csv' --csv_val '/home/subSda/KAIST/val_annots.csv' 

output:
/usr/local/lib/python3.5/dist-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
CUDA available: True
Traceback (most recent call last):
  File "/home/subSda/pytorch-retinanet/dataloader.py", line 154, in __init__
    self.image_data = self._read_annotations(csv.reader(file, delimiter=','), self.classes)
  File "/home/subSda/pytorch-retinanet/dataloader.py", line 278, in _read_annotations
    raise ValueError('line {}: x2 ({}) must be higher than x1 ({})'.format(line, x2, x1))
ValueError: line 6594: x2 (620) must be higher than x1 (620)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 179, in <module>
    main()
  File "train.py", line 66, in main
    dataset_train = CSVDataset(train_file=parser.csv_train, class_list=parser.csv_classes, transform=transforms.Compose([Normalizer(), Augmenter(), Resizer()]))
  File "/home/subSda/pytorch-retinanet/dataloader.py", line 156, in __init__
    raise_from(ValueError('invalid CSV annotations file: {}: {}'.format(self.train_file, e)), None)
NameError: name 'raise_from' is not defined

`

how to solve this problem? thank all help

**Comment by ViswanathaReddyGajjala** [comment]
Change it to 'raise' instead of 'raise_from'. After that try to figure out the error. Your bounding boxes should follow the format xmin, ymin, xmax, ymax. I think you have a problem with the data format.
1) If you are sure that your data format is correct then comment out these four lines
```
if x2 <= x1:
            raise ValueError('line {}: x2 ({}) must be higher than x1 ({})'.format(line, x2, x1))
if y2 <= y1:
            raise ValueError('line {}: y2 ({}) must be higher than y1 ({})'.format(line, y2, y1))
```
 2) x2 (620) must be higher than x1 (620)
 If x1==x2 then also it is showing an exception. So, it's better to comment out those four lines.

**Comment by dspei** [comment]
> Change it to 'raise' instead of 'raise_from'. After that try to figure out the error. Your bounding boxes should follow the format xmin, ymin, xmax, ymax. I think you have a problem with the data format.
> 
> 1. If you are sure that your data format is correct then comment out these four lines
> 
> ```
> if x2 <= x1:
>             raise ValueError('line {}: x2 ({}) must be higher than x1 ({})'.format(line, x2, x1))
> if y2 <= y1:
>             raise ValueError('line {}: y2 ({}) must be higher than y1 ({})'.format(line, y2, y1))
> ```
> 
> 1. x2 (620) must be higher than x1 (620)
>    If x1==x2 then also it is showing an exception. So, it's better to comment out those four lines.

thans， it s work
