### ISSUE TITLE
Image file is truncated (4 bytes not processed)

### ISSUE THREAD

**Issue by SalahAdDin** [yhenon/pytorch-retinanet#93]
Hello,

I was implementing this system and i got an error:
```
Epoch: 0 | Iteration: 46941 | Classification loss: 0.39337 | Regression loss: 0.51541 | Running loss: 0.83944
Epoch: 0 | Iteration: 46942 | Classification loss: 0.26286 | Regression loss: 0.14560 | Running loss: 0.83871
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    main()
  File "train.py", line 125, in main
    for iter_num, data in enumerate(dataloader_train):
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/imageio/plugins/pillow.py", line 518, in pil_try_read
    im.getdata()[0]
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/PIL/Image.py", line 1308, in getdata
    self.load()
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/PIL/ImageFile.py", line 249, in load
    "(%d bytes not processed)" % len(b)
OSError: image file is truncated (4 bytes not processed)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/dataloader.py", line 65, in __getitem__
    img = self.load_image(idx)
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/dataloader.py", line 76, in load_image
    img = skimage.io.imread(path)
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/imageio/core/functions.py", line 221, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/imageio/core/functions.py", line 143, in get_reader
    return format.get_reader(request)
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/imageio/core/format.py", line 164, in get_reader
    return self.Reader(self, request)
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/imageio/core/format.py", line 214, in __init__
    self._open(**self.request.kwargs.copy())
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/imageio/plugins/pillow.py", line 423, in _open
    return PillowFormat.Reader._open(self, pilmode=pilmode, as_gray=as_gray)
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/imageio/plugins/pillow.py", line 137, in _open
    pil_try_read(self._im)
  File "/home/joselito92/Projects/thesis/retinanet/pytorch-retinanet/lib/python3.7/site-packages/imageio/plugins/pillow.py", line 529, in pil_try_read
    raise ValueError(error_message)
ValueError: Could not load "" 
Reason: "image file is truncated (4 bytes not processed)"
Please see documentation at: http://pillow.readthedocs.io/en/latest/installation.html#external-libraries
```

Why?

**Comment by huangzicheng** [comment]
in dataloader.py add this:
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
