### ISSUE TITLE
Help!An error occured while evaluating

### ISSUE THREAD

**Issue by LYH-YNU** [yhenon/pytorch-retinanet#94]
Evaluating dataset
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    main()
  File "train.py", line 161, in main
    coco_eval.evaluate_coco(dataset_val, retinanet)
  File "/home/liyh/github/pytorch-retinanet/coco_eval.py", line 27, in evaluate_coco
    scores, labels, boxes = model(data['img'].permute(2, 0, 1).cuda().float().unsqueeze(dim=0))
  File "/home/liyh/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/liyh/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/home/liyh/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/liyh/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 67, in gather
    return gather_map(outputs)
  File "/home/liyh/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/liyh/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 54, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/liyh/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
    assert all(map(lambda i: i.is_cuda, inputs))
AssertionError
I have no idea about the error above, could any one help me?

**Comment by WeiXuVanG** [comment]
I got the same error.I haven't solved it yet.

**Comment by LYH-YNU** [comment]
> I got the same error.I haven't solved it yet.

It seems some of the images in validation set did not be put in GPU while evaluating,I am trying to find a solution.

**Comment by LYH-YNU** [comment]
Have a look at #35,there is a solution.

**Comment by WeiXuVanG** [comment]
Thanks very much！ It works!
