### ISSUE TITLE
dist must be a Distribution instance

### ISSUE THREAD

**Issue by klauscf** [yhenon/pytorch-retinanet#97]
(base) klaus@ubuntu:~/Desktop/pytorch-retinanet/lib$ bash build.sh 
Compiling nms kernels by nvcc...
Including CUDA code.
/home/klaus/Desktop/pytorch-retinanet/lib/nms
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    extra_compile_args=['-std=c99']
  File "/home/klaus/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 228, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/home/klaus/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/home/klaus/conda/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance

i do not know what the problems is!!! does anybody know,please tell me!

**Comment by 1165628028** [comment]
I also meet it, do you solve it?

**Comment by miaowumonsyer** [comment]
syr@amax:~/retinanet-masking/lib$ bash "/home/syr/retinanet-masking/lib/build.sh"
Compiling nms kernels by nvcc...
nvcc fatal   : Unsupported gpu architecture 'compute_30'
Including CUDA code.
/home/syr/retinanet-masking/lib/nms
Traceback (most recent call last):
  File "build.py", line 24, in <module>
    ffi = BuildExtension(
  File "/opt/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 378, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 172, in __init__
    _Command.__init__(self, dist)
  File "/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")

I can't compile it too!!
